# -*- coding: utf-8 -*-

#Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox,QApplication,QWidget,QPushButton
import random

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1340, 465)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # ##############################  Label  ##########################################
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 50, 1121, 80))
        self.frame.setStyleSheet("background-color: rgb(204, 203, 198);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 1101, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Himalaya")
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")

        # ##############################  Input Username  ##########################################
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(230, 170, 201, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        # ##############################  Input Password  ##########################################
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 220, 201, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 230, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        # ##############################  Input Website  ##########################################
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(230, 270, 201, 31))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 280, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        # ##############################  Input Keyword  ##########################################
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(230, 320, 201, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 330, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        
        # ##############################  Central Line  ##########################################
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(460, 160, 20, 281))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(470, 160, 20, 281))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        # ##############################  Input Site  ##########################################
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(510, 180, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(590, 170, 221, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")

        # ##############################  Input Passcode  ##########################################
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(510, 230, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(590, 220, 221, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Password)
        # ##############################  Input Text  ##########################################
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(510, 270, 301, 91))
        self.textEdit.setObjectName("textEdit")

        # ##############################  Submit Button  ##########################################
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 380, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.submit)

        # ##############################  Search Button  ##########################################
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 380, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.search)

        # ##############################  Kavruk Image  ##########################################
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(830, 170, 361, 241))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("KavrukTechnologiesP_1.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")

        # ##############################  End  ##########################################
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1407, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def submit(self):
        print("clicked submit")
        user = self.lineEdit.text()
        passc = self.lineEdit_2.text()
        web = self.lineEdit_3.text()
        key = self.lineEdit_4.text()

        hasnum = False
        hasup = False
        haslo = False
        haspecial = False
        haslen = len(passc) >= 8
        special_characters = "!@#$%^&*()?/"
        for i in range(len(passc)):      
            c = passc[i]
            if c.isdigit():
                hasnum = True
            elif c.isupper():
                hasup = True
            elif c.islower():
                haslo = True
            elif c in special_characters:
                haspecial = True
        ### Condition to check whether the given password has passed all the above conditions ###
        if hasnum==True and hasup==True and haslo==True and haspecial==True and haslen==True:
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setText("Entry Successful")
            msgBox.setWindowTitle("Password Manager")
            msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
            returnValue = msgBox.exec()

            ###### Database Integration ######
            conn = sqlite3.connect('password.sqlite')
            cur = conn.cursor()
            task = (user,passc,web)
            cur.execute('INSERT INTO pass (user,pass,web) values (?,?,?)',task)
            conn.commit()
            conn.close()
        else:
            special="!@#$%^&*()?/"
            suggest=""
            i=0
            while i<4:
                while len(key)<8:
                    key=key+chr(random.randint(ord('a'),ord('z')))
                key+=str(random.randint(0,9))
                key+=str(random.choice(special))
                key=key.capitalize()
                suggest+=key+'\n'
                i=i+1
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setWindowTitle("Password Manager")
            msgBox.setText("Your password didn't meet the standards.")
            s="Your password should meet the conditions mentions below \n 1. At least 1 Uppercase \n 2. At least 1 lower case \n 3. At least 1 number \n 4. At least 1 special character \n 5. At least 8 characters."
            msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
            msgBox.setInformativeText("Password Suggestions: "+str(suggest))#show a msg in the qmsg box
            msgBox.setDetailedText(s)#to create a hide details option in the msg box
            returnValue = msgBox.exec()


    def search(self):
        print("clicked search")
        we = self.lineEdit_5.text()
        paz = self.lineEdit_6.text()
        if paz=='root':#if users enters root only the search buttons works
            
            conn = sqlite3.connect('password.sqlite')
            cur = conn.cursor()
            cur.execute("SELECT * FROM pass WHERE web=?",[we])#fetching username and password using website name

            rows = cur.fetchall()
            for row in rows:
                print(row)
            self.textEdit.setText(" Username \t Password \n\n "+str(rows[-1][0])+" \t "+str(rows[-1][1]))
            
            conn.commit()
            conn.close()

        else:
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Critical)
            msgBox.setWindowTitle("Password Manager")
            msgBox.setText("Wrong password. Please try again!!")
            msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)    
            returnValue = msgBox.exec()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Kavruk Safe Locker"))
        self.label_2.setText(_translate("MainWindow", "Username"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label_4.setText(_translate("MainWindow", "Website"))
        self.label_5.setText(_translate("MainWindow", "Keyword"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.label_6.setText(_translate("MainWindow", "Site"))
        self.label_7.setText(_translate("MainWindow", "Passcode"))
        self.pushButton_2.setText(_translate("MainWindow", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
